using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Armor;
using Content.Shared.Inventory;
using Content.Shared.Damage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Stalker_EN.Examine;

/// <summary>
/// Window for displaying armor stat comparisons between examined and equipped items.
/// Shows coefficient protections with progress bars and flat reductions as numeric values.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class StatsExamineWindow : FancyWindow
{
    /// <summary>
    /// Holds all stats for weapon comparison.
    /// </summary>
    public record WeaponComparisonStats(
        DamageModifierSet ExaminedModifiers,
        int? ExaminedArmorClass,
        float? ExaminedReflectProb,
        DamageModifierSet? EquippedModifiers,
        int? EquippedArmorClass,
        float? EquippedReflectProb,
        float? ExaminedSpread,
        float? ExaminedStability,
        float? EquippedSpread,
        float? EquippedStability,
        float? ExaminedFireRate,
        float? EquippedFireRate,
        float? ExaminedPveDamage,
        float? ExaminedPvpDamage,
        Dictionary<string, float>? ExaminedDamageTypes,
        string? ExaminedCartridgeId,
        Dictionary<string, float>? ExaminedPveDamageTypes,
        float? EquippedPveDamage,
        float? EquippedPvpDamage,
        Dictionary<string, float>? EquippedDamageTypes,
        string? EquippedCartridgeId,
        Dictionary<string, float>? EquippedPveDamageTypes,
        string? ExaminedWeaponName,
        string? EquippedWeaponName);

    public StatsExamineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    /// <summary>
    /// Updates the stats display with armor stat comparison data.
    /// Shows armor class, reflect chance, coefficient protections, and flat reductions.
    /// </summary>
    public void UpdateArmorStats(
        DamageModifierSet examinedModifiers,
        int? examinedArmorClass,
        float? examinedReflectProb,
        DamageModifierSet? equippedModifiers,
        int? equippedArmorClass,
        float? equippedReflectProb)
    {
        StatsContainer.Children.Clear();

        AddArmorStatRows(examinedModifiers, equippedModifiers, examinedArmorClass, equippedArmorClass, examinedReflectProb, equippedReflectProb);
    }

    /// <summary>
    /// Adds armor stat rows to the display. Helper method to avoid duplication between UpdateArmorStats and UpdateStats.
    /// </summary>
    private void AddArmorStatRows(
        DamageModifierSet examinedModifiers,
        DamageModifierSet? equippedModifiers,
        int? examinedArmorClass,
        int? equippedArmorClass,
        float? examinedReflectProb,
        float? equippedReflectProb)
    {
        // Show coefficient protections
        foreach (var (damageType, coefficient) in examinedModifiers.Coefficients)
        {
            var protectionPercent = (1f - coefficient) * 100f;
            var statName = Loc.GetString($"armor-damage-type-{damageType.ToLower()}");

            float? equippedProtection = null;
            if (equippedModifiers?.Coefficients.TryGetValue(damageType, out var equippedCoeff) == true)
            {
                equippedProtection = (1f - equippedCoeff) * 100f;
            }

            AddStatRow(statName, protectionPercent, equippedProtection);
        }

        // Show coefficients that exist in equipped armor but not in examined
        if (equippedModifiers != null)
        {
            foreach (var (damageType, coefficient) in equippedModifiers.Coefficients)
            {
                if (!examinedModifiers.Coefficients.ContainsKey(damageType))
                {
                    var protectionPercent = (1f - coefficient) * 100f;
                    var statName = Loc.GetString($"armor-damage-type-{damageType.ToLower()}");
                    AddStatRow(statName, 0, protectionPercent, isMissing: true);
                }
            }
        }

        // Show flat reductions
        foreach (var (damageType, reduction) in examinedModifiers.FlatReduction)
        {
            var statName = Loc.GetString($"armor-damage-type-{damageType.ToLower()}");

            float? equippedReduction = null;
            if (equippedModifiers?.FlatReduction.TryGetValue(damageType, out var equippedFlat) == true)
            {
                equippedReduction = equippedFlat;
            }

            AddStatRow(statName, reduction, equippedReduction, isFlatReduction: true);
        }

        // Show flat reductions that exist in equipped armor but not in examined
        if (equippedModifiers != null)
        {
            foreach (var (damageType, reduction) in equippedModifiers.FlatReduction)
            {
                if (!examinedModifiers.FlatReduction.ContainsKey(damageType))
                {
                    var statName = Loc.GetString($"armor-damage-type-{damageType.ToLower()}");
                    AddStatRow(statName, 0, reduction, isFlatReduction: true, isMissing: true);
                }
            }
        }

        // Show Armor Class if available (Stalker-specific) - treat like flat reduction (no progress bar)
        if (examinedArmorClass.HasValue)
        {
            AddStatRow(
                $"Armor Class",
                examinedArmorClass.Value,
                equippedArmorClass,
                isFlatReduction: true
            );
        }
        else if (equippedArmorClass.HasValue)
        {
            // Show armor class from equipped armor as missing (red)
            AddStatRow(
                $"Armor Class",
                0,
                equippedArmorClass,
                isFlatReduction: true,
                isMissing: true
            );
        }

        // Show Reflect Chance if available (for helmets)
        if (examinedReflectProb.HasValue)
        {
            AddStatRow(
                $"Reflect Chance",
                examinedReflectProb.Value * 100f,
                equippedReflectProb.HasValue ? equippedReflectProb.Value * 100f : null,
                isFlatReduction: true
            );
        }
        else if (equippedReflectProb.HasValue)
        {
            // Show reflect chance from equipped armor as missing (red)
            AddStatRow(
                $"Reflect Chance",
                0,
                equippedReflectProb.Value * 100f,
                isFlatReduction: true,
                isMissing: true
            );
        }
    }

    /// <summary>
    /// Updates the stats display with armor and weapon stat comparison data.
    /// Shows armor class, reflect chance, coefficient protections, flat reductions, fire rate, spread, stability, and damage.
    /// </summary>
    public void UpdateStats(WeaponComparisonStats stats)
    {
        StatsContainer.Children.Clear();

        // Show comparison label with weapon names
        if (stats.ExaminedWeaponName != null || stats.EquippedWeaponName != null)
        {
            var comparisonRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(0, 0, 0, 8)
            };

            var comparisonLabel = new Label
            {
                Text = $"{stats.ExaminedWeaponName ?? "Examined"} vs {stats.EquippedWeaponName ?? "Equipped"}",
                FontColorOverride = new Color(0.5f, 0.5f, 0.5f), // Darker gray for comparison label
                HorizontalExpand = true,
                HorizontalAlignment = Control.HAlignment.Center
            };

            comparisonRow.AddChild(comparisonLabel);
            StatsContainer.AddChild(comparisonRow);
        }

        // Show cartridge IDs being compared
        if (stats.ExaminedCartridgeId != null || stats.EquippedCartridgeId != null)
        {
            var cartridgeRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(0, 0, 0, 8)
            };

            var cartridgeLabel = new Label
            {
                Text = "Cartridge: ",
                Margin = new Thickness(0, 0, 8, 0),
                FontColorOverride = new Color(0.7f, 0.7f, 0.7f) // Gray for label
            };

            var cartridgeValue = new Label
            {
                Text = $"{stats.ExaminedCartridgeId ?? "N/A"} vs {stats.EquippedCartridgeId ?? "N/A"}",
                FontColorOverride = new Color(1f, 1f, 1f) // White for value
            };

            cartridgeRow.AddChild(cartridgeLabel);
            cartridgeRow.AddChild(cartridgeValue);
            StatsContainer.AddChild(cartridgeRow);
        }

        // Show PvE DMG (with Mutant) - raw damage with individual damage types
        if (stats.ExaminedPveDamage.HasValue)
        {
            AddStatRow("PvE DMG (raw)", stats.ExaminedPveDamage.Value, stats.EquippedPveDamage, isFlatReduction: true);

            // Show individual damage types for PvE in compact row
            if (stats.ExaminedPveDamageTypes != null)
            {
                AddCompactDamageTypesRow(stats.ExaminedPveDamageTypes, stats.EquippedPveDamageTypes, isPve: true);
            }
        }

        // Show PvP DMG (without Mutant) - raw damage with individual damage types
        if (stats.ExaminedPvpDamage.HasValue && stats.ExaminedDamageTypes != null)
        {
            AddStatRow("PvP DMG (raw)", stats.ExaminedPvpDamage.Value, stats.EquippedPvpDamage, isFlatReduction: true);

            // Show individual damage types for PvP in compact row
            AddCompactDamageTypesRow(stats.ExaminedDamageTypes, stats.EquippedDamageTypes, isPve: false);
        }

        // Show individual stats for Spread, Stability, Fire Rate
        if (stats.ExaminedFireRate.HasValue)
        {
            AddStatRow("Fire Rate", stats.ExaminedFireRate.Value, stats.EquippedFireRate, isFlatReduction: true);
        }

        if (stats.ExaminedSpread.HasValue)
        {
            AddStatRow("Spread", stats.ExaminedSpread.Value, stats.EquippedSpread);
        }

        if (stats.ExaminedStability.HasValue)
        {
            AddStatRow("Stability", stats.ExaminedStability.Value, stats.EquippedStability);
        }

        // Show Armor Class if available (Stalker-specific) - treat like flat reduction (no progress bar)
        if (stats.ExaminedArmorClass.HasValue)
        {
            AddStatRow(
                $"Armor Class",
                stats.ExaminedArmorClass.Value,
                stats.EquippedArmorClass,
                isFlatReduction: true
            );
        }
        else if (stats.EquippedArmorClass.HasValue)
        {
            // Show armor class from equipped armor as missing (red)
            AddStatRow(
                $"Armor Class",
                0,
                stats.EquippedArmorClass,
                isFlatReduction: true,
                isMissing: true
            );
        }

        // Show Reflect Chance if available (for helmets)
        if (stats.ExaminedReflectProb.HasValue)
        {
            AddStatRow(
                $"Reflect Chance",
                stats.ExaminedReflectProb.Value * 100f,
                stats.EquippedReflectProb.HasValue ? stats.EquippedReflectProb.Value * 100f : null,
                isFlatReduction: true
            );
        }
        else if (stats.EquippedReflectProb.HasValue)
        {
            // Show reflect chance from equipped armor as missing (red)
            AddStatRow(
                $"Reflect Chance",
                0,
                stats.EquippedReflectProb.Value * 100f,
                isFlatReduction: true,
                isMissing: true
            );
        }

        // Show armor stats (coefficients, flat reductions, armor class, reflect chance)
        AddArmorStatRows(stats.ExaminedModifiers, stats.EquippedModifiers, stats.ExaminedArmorClass, stats.EquippedArmorClass, stats.ExaminedReflectProb, stats.EquippedReflectProb);
    }

    /// <summary>
    /// Adds a compact horizontal row for damage types (M, B, S, P).
    /// Displays all damage types with their values next to them in a single line.
    /// </summary>
    private void AddCompactDamageTypesRow(Dictionary<string, float> examinedTypes, Dictionary<string, float>? equippedTypes, bool isPve)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 8)
        };

        // Order of damage types: Mutant (M), Blunt (B), Slash (S), Piercing (P)
        var damageTypeOrder = new List<string> { "Mutant", "Blunt", "Slash", "Piercing" };

        // Collect all unique damage types from both examined and equipped
        var allDamageTypes = new HashSet<string>(examinedTypes.Keys);
        if (equippedTypes != null)
        {
            foreach (var key in equippedTypes.Keys)
                allDamageTypes.Add(key);
        }

        foreach (var damageType in damageTypeOrder)
        {
            // For PvP, skip Mutant
            if (!isPve && damageType == "Mutant")
                continue;

            // Only show if this damage type exists in either examined or equipped
            if (!allDamageTypes.Contains(damageType))
                continue;

            var shortName = GetDamageTypeShortName(damageType);
            float? examinedValue = examinedTypes.TryGetValue(damageType, out var examinedVal) ? examinedVal : null;
            float? equippedValue = equippedTypes != null && equippedTypes.TryGetValue(damageType, out var equippedVal) ? equippedVal : null;

            // If damage type exists in equipped but not in examined, show as missing (red)
            if (examinedValue == null && equippedValue.HasValue)
            {
                var container = CreateCompactStatLabel(shortName, 0f, equippedValue, isFlatReduction: true);
                row.AddChild(container);
            }
            // If damage type exists in examined (with or without equipped value)
            else if (examinedValue.HasValue)
            {
                var container = CreateCompactStatLabel(shortName, examinedValue.Value, equippedValue, isFlatReduction: true);
                row.AddChild(container);
            }
        }

        if (row.ChildCount > 0)
            StatsContainer.AddChild(row);
    }

    /// <summary>
    /// Creates a compact stat label with abbreviation and value.
    /// </summary>
    private BoxContainer CreateCompactStatLabel(string label, float examinedValue, float? equippedValue, bool isFlatReduction)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 0, 16, 0)
        };

        // Label (P, S, B)
        var labelControl = new Label
        {
            Text = label,
            FontColorOverride = new Color(0.7f, 0.7f, 0.7f),
            Margin = new Thickness(0, 0, 4, 0),
            ToolTip = GetTooltipText(label)
        };
        container.AddChild(labelControl);

        // Examined value
        var examinedLabel = new Label
        {
            Text = isFlatReduction ? $"{examinedValue:F1}" : $"{examinedValue:F0}%",
            FontColorOverride = new Color(1f, 1f, 1f)
        };
        container.AddChild(examinedLabel);

        // Delta indicator
        if (equippedValue.HasValue)
        {
            var delta = examinedValue - equippedValue.Value;
            var deltaLabel = new Label
            {
                Text = delta > 0 ? $" (+{delta:F1})" : delta < 0 ? $" ({delta:F1})" : "",
                FontColorOverride = delta > 0 ? new Color(0.298f, 0.686f, 0.314f) : delta < 0 ? new Color(0.957f, 0.263f, 0.212f) : new Color(0.5f, 0.5f, 0.5f)
            };
            container.AddChild(deltaLabel);
        }

        return container;
    }

    /// <summary>
    /// Gets tooltip text for a stat label.
    /// </summary>
    private string GetTooltipText(string label)
    {
        return label switch
        {
            "PvE DMG (raw)" => "Total PvE damage including all damage types (Mutant, Blunt, Slash, Piercing). Uses cartridge class 0 for most weapons, class 1 for shotguns.",
            "PvP DMG (raw)" => "Total PvP damage excluding Mutant damage (Blunt, Slash, Piercing only). Uses cartridge class 2 for most weapons, class 1 for shotguns.",
            "Spread" => "Weapon spread - accuracy of shots. Lower is better. Calculated from min/max angle with 95° reference.",
            "Stability" => "Weapon stability - recoil recovery. Higher is better. Calculated from angle decay, angle increase, and fire rate.",
            _ => ""
        };
    }

    /// <summary>
    /// Adds a stat row to the display with optional comparison highlighting.
    /// </summary>
    private void AddStatRow(
        string statName,
        float examinedValue,
        float? equippedValue,
        bool isFlatReduction = false,
        bool isMissing = false)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2)
        };

        // Check if this stat should be a button (Spread, Stability, PvE DMG, PvP DMG)
        var isButtonStat = statName == "Spread" || statName == "Stability" ||
                           statName == "PvE DMG (raw)" || statName == "PvP DMG (raw)";

        // Stat name label or button
        Control statNameControl;
        if (isButtonStat)
        {
            var button = new Button
            {
                Text = statName,
                HorizontalExpand = false,
                MinWidth = 120,
                StyleClasses = { "ButtonDefault" },
                ToolTip = GetTooltipText(statName)
            };
            statNameControl = button;
        }
        else
        {
            var label = new Label
            {
                Text = statName,
                HorizontalExpand = false,
                MinWidth = 120
            };
            statNameControl = label;
        }
        row.AddChild(statNameControl);

        // Progress bar for coefficients, spacer for flat reductions
        if (!isFlatReduction)
        {
            var barContainer = new PanelContainer
            {
                StyleClasses = { "ProgressBarBackground" },
                HorizontalExpand = true,
                MinSize = new Vector2(100, 16),
                Margin = new Thickness(4, 0)
            };

            var progressBar = new ProgressBar
            {
                MinValue = 0,
                MaxValue = 100,
                Value = Math.Clamp(examinedValue, 0, 100),
                HorizontalExpand = true
            };
            barContainer.AddChild(progressBar);
            row.AddChild(barContainer);
        }
        else
        {
            // Spacer for flat reductions
            var spacer = new Control
            {
                HorizontalExpand = true,
                MinSize = new Vector2(100, 16)
            };
            row.AddChild(spacer);
        }

        // Value label with comparison
        var valueLabel = new Label
        {
            Text = isFlatReduction ? $"{examinedValue:F1}" : $"{examinedValue:F1}%",
            HorizontalExpand = false,
            MinWidth = 50,
            HorizontalAlignment = Control.HAlignment.Right
        };

        if (isMissing)
        {
            // Stat doesn't exist in examined armor but exists in equipped - show as red (worse)
            valueLabel.Text += $" ↓ -{equippedValue!.Value:F1}";
            valueLabel.Modulate = new Color(0.957f, 0.263f, 0.212f); // #f44336 red
        }
        else if (equippedValue.HasValue)
        {
            var delta = examinedValue - equippedValue.Value;
            if (delta > 0.01f)
            {
                // Examined is BETTER
                valueLabel.Text += $" ↑ +{delta:F1}";
                valueLabel.Modulate = new Color(0.298f, 0.686f, 0.314f); // #4caf50 green
            }
            else if (delta < -0.01f)
            {
                // Examined is WORSE
                valueLabel.Text += $" ↓ {delta:F1}";
                valueLabel.Modulate = new Color(0.957f, 0.263f, 0.212f); // #f44336 red
            }
        }
        else
        {
            // Stat doesn't exist in equipped armor - highlight green
            valueLabel.Modulate = new Color(0.298f, 0.686f, 0.314f); // #4caf50 green
        }

        row.AddChild(valueLabel);
        StatsContainer.AddChild(row);
    }

    /// <summary>
    /// Converts damage type names to short abbreviations for display.
    /// </summary>
    private string GetDamageTypeShortName(string damageType)
    {
        return damageType switch
        {
            "Piercing" => "P",
            "Slash" => "S",
            "Blunt" => "B",
            "Mutant" => "M",
            _ => damageType.Substring(0, Math.Min(2, damageType.Length))
        };
    }
}
