using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Armor;
using Content.Shared.Inventory;
using Content.Shared.Damage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Stalker_EN.Examine;

/// <summary>
/// Window for displaying armor stat comparisons between examined and equipped items.
/// Shows coefficient protections with progress bars and flat reductions as numeric values.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class StatsExamineWindow : FancyWindow
{
    public StatsExamineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    /// <summary>
    /// Updates the stats display with armor stat comparison data.
    /// Shows armor class, reflect chance, coefficient protections, and flat reductions.
    /// </summary>
    public void UpdateArmorStats(
        DamageModifierSet examinedModifiers,
        int? examinedArmorClass,
        float? examinedReflectProb,
        DamageModifierSet? equippedModifiers,
        int? equippedArmorClass,
        float? equippedReflectProb)
    {
        StatsContainer.Children.Clear();

        // Show coefficient protections
        foreach (var (damageType, coefficient) in examinedModifiers.Coefficients)
        {
            var protectionPercent = (1f - coefficient) * 100f;
            var statName = Loc.GetString($"armor-damage-type-{damageType.ToLower()}");

            float? equippedProtection = null;
            if (equippedModifiers?.Coefficients.TryGetValue(damageType, out var equippedCoeff) == true)
            {
                equippedProtection = (1f - equippedCoeff) * 100f;
            }

            AddStatRow(statName, protectionPercent, equippedProtection);
        }

        // Show coefficients that exist in equipped armor but not in examined
        if (equippedModifiers != null)
        {
            foreach (var (damageType, coefficient) in equippedModifiers.Coefficients)
            {
                if (!examinedModifiers.Coefficients.ContainsKey(damageType))
                {
                    var protectionPercent = (1f - coefficient) * 100f;
                    var statName = Loc.GetString($"armor-damage-type-{damageType.ToLower()}");
                    AddStatRow(statName, 0, protectionPercent, isMissing: true);
                }
            }
        }

        // Show flat reductions
        foreach (var (damageType, reduction) in examinedModifiers.FlatReduction)
        {
            var statName = Loc.GetString($"armor-damage-type-{damageType.ToLower()}");

            float? equippedReduction = null;
            if (equippedModifiers?.FlatReduction.TryGetValue(damageType, out var equippedFlat) == true)
            {
                equippedReduction = equippedFlat;
            }

            AddStatRow(statName, reduction, equippedReduction, isFlatReduction: true);
        }

        // Show flat reductions that exist in equipped armor but not in examined
        if (equippedModifiers != null)
        {
            foreach (var (damageType, reduction) in equippedModifiers.FlatReduction)
            {
                if (!examinedModifiers.FlatReduction.ContainsKey(damageType))
                {
                    var statName = Loc.GetString($"armor-damage-type-{damageType.ToLower()}");
                    AddStatRow(statName, 0, reduction, isFlatReduction: true, isMissing: true);
                }
            }
        }

        // Show Armor Class if available (Stalker-specific) - treat like flat reduction (no progress bar)
        if (examinedArmorClass.HasValue)
        {
            AddStatRow(
                $"Armor Class",
                examinedArmorClass.Value,
                equippedArmorClass,
                isFlatReduction: true
            );
        }
        else if (equippedArmorClass.HasValue)
        {
            // Show armor class from equipped armor as missing (red)
            AddStatRow(
                $"Armor Class",
                0,
                equippedArmorClass,
                isFlatReduction: true,
                isMissing: true
            );
        }

        // Show Reflect Chance if available (for helmets)
        if (examinedReflectProb.HasValue)
        {
            AddStatRow(
                $"Reflect Chance",
                examinedReflectProb.Value * 100f,
                equippedReflectProb.HasValue ? equippedReflectProb.Value * 100f : null,
                isFlatReduction: true
            );
        }
        else if (equippedReflectProb.HasValue)
        {
            // Show reflect chance from equipped armor as missing (red)
            AddStatRow(
                $"Reflect Chance",
                0,
                equippedReflectProb.Value * 100f,
                isFlatReduction: true,
                isMissing: true
            );
        }
    }

    /// <summary>
    /// Updates the stats display with armor and weapon stat comparison data.
    /// Shows armor class, reflect chance, coefficient protections, flat reductions, fire rate, spread, stability, damage, and falloff.
    /// </summary>
    public void UpdateStats(
        DamageModifierSet examinedModifiers,
        int? examinedArmorClass,
        float? examinedReflectProb,
        DamageModifierSet? equippedModifiers,
        int? equippedArmorClass,
        float? equippedReflectProb,
        float? examinedSpread = null,
        float? examinedStability = null,
        float? equippedSpread = null,
        float? equippedStability = null,
        float? examinedFireRate = null,
        float? equippedFireRate = null,
        float? examinedPveDamage = null,
        float? examinedPvpDamage = null,
        Dictionary<string, float>? examinedDamageTypes = null,
        float? examinedFalloff = null,
        string? examinedCartridgeId = null,
        Dictionary<string, float>? examinedPveDamageTypes = null,
        float? equippedPveDamage = null,
        float? equippedPvpDamage = null,
        Dictionary<string, float>? equippedDamageTypes = null,
        float? equippedFalloff = null,
        string? equippedCartridgeId = null,
        Dictionary<string, float>? equippedPveDamageTypes = null,
        string? examinedWeaponName = null,
        string? equippedWeaponName = null)
    {
        StatsContainer.Children.Clear();

        // Show comparison label with weapon names
        if (examinedWeaponName != null || equippedWeaponName != null)
        {
            var comparisonRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(0, 0, 0, 8)
            };

            var comparisonLabel = new Label
            {
                Text = $"{examinedWeaponName ?? "Examined"} vs {equippedWeaponName ?? "Equipped"}",
                FontColorOverride = new Color(0.5f, 0.5f, 0.5f), // Darker gray for comparison label
                HorizontalExpand = true,
                HorizontalAlignment = Control.HAlignment.Center
            };

            comparisonRow.AddChild(comparisonLabel);
            StatsContainer.AddChild(comparisonRow);
        }

        // Show cartridge IDs being compared
        if (examinedCartridgeId != null || equippedCartridgeId != null)
        {
            var cartridgeRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(0, 0, 0, 8)
            };

            var cartridgeLabel = new Label
            {
                Text = "Cartridge: ",
                Margin = new Thickness(0, 0, 8, 0),
                FontColorOverride = new Color(0.7f, 0.7f, 0.7f) // Gray for label
            };

            var cartridgeValue = new Label
            {
                Text = $"{examinedCartridgeId ?? "N/A"} vs {equippedCartridgeId ?? "N/A"}",
                FontColorOverride = new Color(1f, 1f, 1f) // White for value
            };

            cartridgeRow.AddChild(cartridgeLabel);
            cartridgeRow.AddChild(cartridgeValue);
            StatsContainer.AddChild(cartridgeRow);
        }

        // Show PvE DMG (with Mutant) - raw damage with individual damage types
        if (examinedPveDamage.HasValue)
        {
            AddStatRow("PvE DMG (raw)", examinedPveDamage.Value, equippedPveDamage, isFlatReduction: true);

            // Show individual damage types for PvE
            if (examinedPveDamageTypes != null)
            {
                foreach (var (damageType, value) in examinedPveDamageTypes)
                {
                    var shortName = GetDamageTypeShortName(damageType);
                    float? equippedValue = null;
                    if (equippedPveDamageTypes != null && equippedPveDamageTypes.TryGetValue(damageType, out var equippedTypeValue))
                    {
                        equippedValue = equippedTypeValue;
                    }
                    AddStatRow($"  {shortName}", value, equippedValue, isFlatReduction: true);
                }
            }
        }

        // Show PvP DMG (without Mutant) - raw damage with individual damage types
        if (examinedPvpDamage.HasValue && examinedDamageTypes != null)
        {
            AddStatRow("PvP DMG (raw)", examinedPvpDamage.Value, equippedPvpDamage, isFlatReduction: true);

            // Show individual damage types for PvP
            foreach (var (damageType, value) in examinedDamageTypes)
            {
                var shortName = GetDamageTypeShortName(damageType);
                float? equippedValue = null;
                if (equippedDamageTypes != null && equippedDamageTypes.TryGetValue(damageType, out var equippedTypeValue))
                {
                    equippedValue = equippedTypeValue;
                }
                AddStatRow($"  {shortName}", value, equippedValue, isFlatReduction: true);
            }
        }

        if (examinedFalloff.HasValue)
        {
            AddStatRow("Falloff", examinedFalloff.Value, equippedFalloff, isFlatReduction: true);
        }

        if (examinedFireRate.HasValue)
        {
            AddStatRow("Fire Rate", examinedFireRate.Value, equippedFireRate, isFlatReduction: true);
        }

        if (examinedSpread.HasValue)
        {
            AddStatRow("Spread", examinedSpread.Value, equippedSpread);
        }

        if (examinedStability.HasValue)
        {
            AddStatRow("Stability", examinedStability.Value, equippedStability);
        }

        // Show Armor Class if available (Stalker-specific) - treat like flat reduction (no progress bar)
        if (examinedArmorClass.HasValue)
        {
            AddStatRow(
                $"Armor Class",
                examinedArmorClass.Value,
                equippedArmorClass,
                isFlatReduction: true
            );
        }
        else if (equippedArmorClass.HasValue)
        {
            // Show armor class from equipped armor as missing (red)
            AddStatRow(
                $"Armor Class",
                0,
                equippedArmorClass,
                isFlatReduction: true,
                isMissing: true
            );
        }

        // Show Reflect Chance if available (for helmets)
        if (examinedReflectProb.HasValue)
        {
            AddStatRow(
                $"Reflect Chance",
                examinedReflectProb.Value * 100f,
                equippedReflectProb.HasValue ? equippedReflectProb.Value * 100f : null,
                isFlatReduction: true
            );
        }
        else if (equippedReflectProb.HasValue)
        {
            // Show reflect chance from equipped armor as missing (red)
            AddStatRow(
                $"Reflect Chance",
                0,
                equippedReflectProb.Value * 100f,
                isFlatReduction: true,
                isMissing: true
            );
        }

        // Show coefficient protections
        foreach (var (damageType, coefficient) in examinedModifiers.Coefficients)
        {
            var protectionPercent = (1f - coefficient) * 100f;
            var statName = Loc.GetString($"armor-damage-type-{damageType.ToLower()}");

            float? equippedProtection = null;
            if (equippedModifiers?.Coefficients.TryGetValue(damageType, out var equippedCoeff) == true)
            {
                equippedProtection = (1f - equippedCoeff) * 100f;
            }

            AddStatRow(statName, protectionPercent, equippedProtection);
        }

        // Show coefficients that exist in equipped armor but not in examined
        if (equippedModifiers != null)
        {
            foreach (var (damageType, coefficient) in equippedModifiers.Coefficients)
            {
                if (!examinedModifiers.Coefficients.ContainsKey(damageType))
                {
                    var protectionPercent = (1f - coefficient) * 100f;
                    var statName = Loc.GetString($"armor-damage-type-{damageType.ToLower()}");
                    AddStatRow(statName, 0, protectionPercent, isMissing: true);
                }
            }
        }

        // Show flat reductions
        foreach (var (damageType, reduction) in examinedModifiers.FlatReduction)
        {
            var statName = Loc.GetString($"armor-damage-type-{damageType.ToLower()}");

            float? equippedReduction = null;
            if (equippedModifiers?.FlatReduction.TryGetValue(damageType, out var equippedFlat) == true)
            {
                equippedReduction = equippedFlat;
            }

            AddStatRow(statName, reduction, equippedReduction, isFlatReduction: true);
        }

        // Show flat reductions that exist in equipped armor but not in examined
        if (equippedModifiers != null)
        {
            foreach (var (damageType, reduction) in equippedModifiers.FlatReduction)
            {
                if (!examinedModifiers.FlatReduction.ContainsKey(damageType))
                {
                    var statName = Loc.GetString($"armor-damage-type-{damageType.ToLower()}");
                    AddStatRow(statName, 0, reduction, isFlatReduction: true, isMissing: true);
                }
            }
        }
    }

    /// <summary>
    /// Adds a stat row to the display with optional comparison highlighting.
    /// </summary>
    private void AddStatRow(
        string statName,
        float examinedValue,
        float? equippedValue,
        bool isFlatReduction = false,
        bool isMissing = false)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2)
        };

        // Stat name label
        var nameLabel = new Label
        {
            Text = statName,
            HorizontalExpand = false,
            MinWidth = 120
        };
        row.AddChild(nameLabel);

        // Progress bar for coefficients, spacer for flat reductions
        if (!isFlatReduction)
        {
            var barContainer = new PanelContainer
            {
                StyleClasses = { "ProgressBarBackground" },
                HorizontalExpand = true,
                MinSize = new Vector2(100, 16),
                Margin = new Thickness(4, 0)
            };

            var progressBar = new ProgressBar
            {
                MinValue = 0,
                MaxValue = 100,
                Value = Math.Clamp(examinedValue, 0, 100),
                HorizontalExpand = true
            };
            barContainer.AddChild(progressBar);
            row.AddChild(barContainer);
        }
        else
        {
            // Spacer for flat reductions
            var spacer = new Control
            {
                HorizontalExpand = true,
                MinSize = new Vector2(100, 16)
            };
            row.AddChild(spacer);
        }

        // Value label with comparison
        var valueLabel = new Label
        {
            Text = isFlatReduction ? $"{examinedValue:F1}" : $"{examinedValue:F1}%",
            HorizontalExpand = false,
            MinWidth = 50,
            HorizontalAlignment = Control.HAlignment.Right
        };

        if (isMissing)
        {
            // Stat doesn't exist in examined armor but exists in equipped - show as red (worse)
            valueLabel.Text += $" ↓ -{equippedValue!.Value:F1}";
            valueLabel.Modulate = new Color(0.957f, 0.263f, 0.212f); // #f44336 red
        }
        else if (equippedValue.HasValue)
        {
            var delta = examinedValue - equippedValue.Value;
            if (delta > 0.01f)
            {
                // Examined is BETTER
                valueLabel.Text += $" ↑ +{delta:F1}";
                valueLabel.Modulate = new Color(0.298f, 0.686f, 0.314f); // #4caf50 green
            }
            else if (delta < -0.01f)
            {
                // Examined is WORSE
                valueLabel.Text += $" ↓ {delta:F1}";
                valueLabel.Modulate = new Color(0.957f, 0.263f, 0.212f); // #f44336 red
            }
        }
        else
        {
            // Stat doesn't exist in equipped armor - highlight green
            valueLabel.Modulate = new Color(0.298f, 0.686f, 0.314f); // #4caf50 green
        }

        row.AddChild(valueLabel);
        StatsContainer.AddChild(row);
    }

    /// <summary>
    /// Converts damage type names to short abbreviations for display.
    /// </summary>
    private string GetDamageTypeShortName(string damageType)
    {
        return damageType switch
        {
            "Piercing" => "P",
            "Slash" => "S",
            "Blunt" => "B",
            "Mutant" => "M",
            _ => damageType.Substring(0, Math.Min(2, damageType.Length))
        };
    }
}
