using System.Numerics;
using Content.Client._Stalker_EN.FactionRelations;
using Content.Shared._Stalker_EN.Leaderboard;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.Leaderboard;

[GenerateTypedNameReferences]
public sealed partial class STLeaderboardUiFragment : BoxContainer
{
    private SpriteSystem? _spriteSystem;

    private SpriteSystem SpriteSystem => _spriteSystem ??= IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

    public Action? OnRefresh;

    public STLeaderboardUiFragment()
    {
        RobustXamlLoader.Load(this);
        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
    }

    public void UpdateState(List<STLeaderboardEntry> entries)
    {
        EntriesList.RemoveAllChildren();

        if (entries.Count == 0)
        {
            var emptyLabel = new Label
            {
                Text = Loc.GetString("st-leaderboard-empty"),
                Align = Label.AlignMode.Center,
                FontColorOverride = Color.Gray,
            };
            EntriesList.AddChild(emptyLabel);
            return;
        }

        var position = 1;
        foreach (var entry in entries)
        {
            var row = _makeEntry(position, entry);
            EntriesList.AddChild(row);

            var separator = new PanelContainer
            {
                StyleClasses = { "LowDivider" },
                Margin = new Thickness(0, 2),
            };
            EntriesList.AddChild(separator);

            position++;
        }
    }

    private Control _makeEntry(int position, STLeaderboardEntry entry)
    {
        var container = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Margin = new Thickness(8, 4),
            HorizontalExpand = true,
        };

        // Left: faction icon placeholder (64x64)
        var iconPanel = new PanelContainer
        {
            MinSize = new Vector2(64, 64),
            Margin = new Thickness(0, 0, 8, 0),
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#222222"),
            },
        };

        var factionIcon = _getBandIconTexture(entry.BandName);
        iconPanel.AddChild(factionIcon);

        container.AddChild(iconPanel);

        // Right: info block
        var infoBlock = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            VerticalExpand = true,
            HorizontalExpand = true,
        };

        // Name line: "#. Name"
        var nameLine = new RichTextLabel { HorizontalExpand = true, Margin = new Thickness(0, 0, 0, 2) };
        var nameMsg = new FormattedMessage();
        nameMsg.AddMarkupOrThrow($"[b]{position}. {FormattedMessage.EscapeText(entry.CharacterName)}[/b]");
        nameLine.SetMessage(nameMsg);
        infoBlock.AddChild(nameLine);

        // Faction line with relation-based color
        var factionDisplay = entry.BandName ?? Loc.GetString("st-leaderboard-nodata");
        var factionColor = _getRelationColor(entry.BandRelation);
        var factionLine = new RichTextLabel { HorizontalExpand = true, Margin = new Thickness(0, 0, 0, 2) };
        var factionMsg = new FormattedMessage();
        factionMsg.PushColor(factionColor);
        factionMsg.AddText($"{Loc.GetString("st-leaderboard-faction-label")} {factionDisplay}");
        factionMsg.Pop();
        factionLine.SetMessage(factionMsg);
        infoBlock.AddChild(factionLine);

        // Rank line
        var rankDisplay = entry.RankName != null ? Loc.GetString(entry.RankName) : Loc.GetString("st-leaderboard-nodata");
        var rankLine = new RichTextLabel { HorizontalExpand = true };
        var rankMsg = new FormattedMessage();
        rankMsg.AddText($"{Loc.GetString("st-leaderboard-rank-label")} {rankDisplay} {entry.RankIndex}");
        rankLine.SetMessage(rankMsg);
        infoBlock.AddChild(rankLine);

        container.AddChild(infoBlock);
        return container;
    }

    private static Color _getRelationColor(STLeaderboardFactionRelation relation) => relation switch
    {
        STLeaderboardFactionRelation.Same => Color.FromHex("#33CC33"),    // green
        STLeaderboardFactionRelation.Alliance => Color.FromHex("#33CC33"), // green
        STLeaderboardFactionRelation.Neutral => Color.FromHex("#FFD700"),  // yellow
        STLeaderboardFactionRelation.Hostile => Color.FromHex("#FF8800"),  // orange
        STLeaderboardFactionRelation.War => Color.FromHex("#FF4444"),      // red
        _ => Color.FromHex("#CCCCCC"),
    };

    private static readonly ResPath LeaderboardRsiPath = new("/Textures/_Stalker_EN/Interface/Cartridges/leaderboard.rsi");

    private Control _getBandIconTexture(string? bandName)
    {
        SpriteSpecifier specifier;

        if (string.IsNullOrEmpty(bandName) || bandName == "—")
        {
            specifier = new SpriteSpecifier.Rsi(LeaderboardRsiPath, "nodata");
        }
        else
        {
            var patchKey = bandName switch
            {
                "Stalker" or "Loner" => "Loners",
                "Bandit" => "Bandits",
                "Dolg" => "Duty",
                "Sci" or "Scientist" or "Ecologist" => "Ecologist",
                _ => bandName,
            };

            if (STFactionPatchIcons.PatchStates.TryGetValue(patchKey, out var patch))
            {
                specifier = new SpriteSpecifier.Rsi(patch.Rsi, patch.State);
            }
            else
            {
                specifier = new SpriteSpecifier.Rsi(LeaderboardRsiPath, "nodata");
            }
        }

        var texture = SpriteSystem.Frame0(specifier);
        return new TextureRect
        {
            Texture = texture,
            TextureScale = new Vector2(2f, 2f),
            Stretch = TextureRect.StretchMode.KeepCentered,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };
    }
}
